version: "3.8"

#Custom Network
networks:
  inception:
    name: inception
    driver: bridge

#List of Volumes
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ancolmen/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ancolmen/data/wordpress'

#Containers (Mandatory)
services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    init: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql/
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress:42
    init: true
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:42
    init: true
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

# BONUS #
  
  redis:
    container_name: redis
    image: redis:42
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

  ftp:
    container_name: ftp
    image: ftp:42
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "21:21"
      - "40000-50000:40000-50000"
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:42
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - wordpress
    restart: unless-stopped


#static website (not in PHP)
#another service to choose

